export const GET_FILMS_LIST_REQUEST = 'GET_FILMS_LIST_REQUEST';
export const GET_FILMS_LIST_SUCCESS = 'GET_FILMS_LIST_SUCCESS';
export const GET_FILMS_LIST_FAIL = 'GET_FILMS_LIST_FAIL';

export const DELETE_FILM_ITEM_REQUEST = 'DELETE_FILM_ITEM_REQUEST';
export const DELETE_FILM_ITEM_SUCCESS = 'DELETE_FILM_ITEM_SUCCESS';
export const DELETE_FILM_ITEM_FAIL = 'DELETE_FILM_ITEM_FAIL';

export const ADD_FILM_ITEM_REQUEST = 'ADD_FILM_ITEM_REQUEST';
export const ADD_FILM_ITEM_SUCCESS = 'ADD_FILM_ITEM_SUCCESS';
export const ADD_FILM_ITEM_FAIL = 'ADD_FILM_ITEM_FAIL';

export const EDIT_FILM_ITEM_REQUEST = 'EDIT_FILM_ITEM_REQUEST';
export const EDIT_FILM_ITEM_SUCCESS = 'EDIT_FILM_ITEM_SUCCESS';
export const EDIT_FILM_ITEM_FAIL = 'EDIT_FILM_ITEM_FAIL';

export const CHANGE_FILMS_LIST_ORDER = 'CHANGE_FILMS_LIST_ORDER';

export const STATUS_TEXT_SHOW = 'STATUS_TEXT_SHOW';
export const STATUS_TEXT_HIDE = 'STATUS_TEXT_HIDE';

export const GET_ACTORS_LIST_REQUEST = 'GET_ACTORS_LIST_REQUEST';
export const GET_ACTORS_LIST_SUCCESS = 'GET_ACTORS_LIST_SUCCESS';
export const GET_ACTORS_LIST_FAIL = 'GET_ACTORS_LIST_FAIL';

export const ADD_ACTOR_ITEM_REQUEST = 'ADD_ACTOR_ITEM_REQUEST';
export const ADD_ACTOR_ITEM_SUCCESS = 'ADD_ACTOR_ITEM_SUCCESS';
export const ADD_ACTOR_ITEM_FAIL = 'ADD_ACTOR_ITEM_FAIL';

export const DELETE_ACTOR_ITEM_REQUEST = 'DELETE_ACTOR_ITEM_REQUEST';
export const DELETE_ACTOR_ITEM_SUCCESS = 'DELETE_ACTOR_ITEM_SUCCESS';
export const DELETE_ACTOR_ITEM_FAIL = 'DELETE_ACTOR_ITEM_FAIL';
