export const GET_FILMS_LIST_REQUEST = 'GET_FILMS_LIST_REQUEST'
export const GET_FILMS_LIST_SUCCESS = 'GET_FILMS_LIST_SUCCESS'
export const GET_FILMS_LIST_FAIL = 'GET_FILMS_LIST_FAIL'
export const CHANGE_FILMS_LIST_ORDER = 'CHANGE_FILMS_LIST_ORDER'

export const GET_ACTORS_LIST_REQUEST = 'GET_ACTORS_LIST_REQUEST'
export const GET_ACTORS_LIST_SUCCESS = 'GET_ACTORS_LIST_SUCCESS'
export const GET_ACTORS_LIST_FAIL = 'GET_ACTORS_LIST_FAIL'
